name: benchmark

on:
  workflow_dispatch:

permissions:
  contents: read

env:
  JDK: '17'
  DISTRIBUTION: 'zulu'
  GRADLE_COMMAND: './gradlew --no-daemon'

jobs:
  longadder:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK ${{ env.JDK }}
        uses: actions/setup-java@v3
        with:
          java-version: ${{ env.JDK }}
          distribution: ${{ env.DISTRIBUTION }}
      - name: JMH LongAdder
        run: ${{ env.GRADLE_COMMAND }} clean :longadder:jmh

  random:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK ${{ env.JDK }}
        uses: actions/setup-java@v3
        with:
          java-version: ${{ env.JDK }}
          distribution: ${{ env.DISTRIBUTION }}
      - name: JMH java.util.Random
        run: ${{ env.GRADLE_COMMAND }} clean :random:jmh

  log4j2clock:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK ${{ env.JDK }}
        uses: actions/setup-java@v3
        with:
          java-version: ${{ env.JDK }}
          distribution: ${{ env.DISTRIBUTION }}
      - name: JMH log4j2 clock
        run: ${{ env.GRADLE_COMMAND }} clean :log4j2clock:jmh

  uuid:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK ${{ env.JDK }}
        uses: actions/setup-java@v3
        with:
          java-version: ${{ env.JDK }}
          distribution: ${{ env.DISTRIBUTION }}
      - name: JMH UUID generation
        run: ${{ env.GRADLE_COMMAND }} clean :uuid:jmh

  cache:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK ${{ env.JDK }}
        uses: actions/setup-java@v3
        with:
          java-version: ${{ env.JDK }}
          distribution: ${{ env.DISTRIBUTION }}
      - name: JMH Cache
        run: ${{ env.GRADLE_COMMAND }} clean :cache:jmh

  zuul:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK ${{ env.JDK }}
        uses: actions/setup-java@v3
        with:
          java-version: ${{ env.JDK }}
          distribution: ${{ env.DISTRIBUTION }}
      - name: JMH Zuul
        run: ${{ env.GRADLE_COMMAND }} clean :zuul:jmh

  collections:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK ${{ env.JDK }}
        uses: actions/setup-java@v3
        with:
          java-version: ${{ env.JDK }}
          distribution: ${{ env.DISTRIBUTION }}
      - name: JMH Collections
        run: ${{ env.GRADLE_COMMAND }} clean :collections:jmh

  strings:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK ${{ env.JDK }}
        uses: actions/setup-java@v3
        with:
          java-version: ${{ env.JDK }}
          distribution: ${{ env.DISTRIBUTION }}
      - name: JMH Strings
        run: ${{ env.GRADLE_COMMAND }} clean :strings:jmh

  jackson:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK ${{ env.JDK }}
        uses: actions/setup-java@v3
        with:
          java-version: ${{ env.JDK }}
          distribution: ${{ env.DISTRIBUTION }}
      - name: JMH Jackson
        run: ${{ env.GRADLE_COMMAND }} clean :jackson:jmh

  slf4j:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK ${{ env.JDK }}
        uses: actions/setup-java@v3
        with:
          java-version: ${{ env.JDK }}
          distribution: ${{ env.DISTRIBUTION }}
      - name: JMH slf4j
        run: ${{ env.GRADLE_COMMAND }} clean :slf4j:jmh

  httpheaders:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK ${{ env.JDK }}
        uses: actions/setup-java@v3
        with:
          java-version: ${{ env.JDK }}
          distribution: ${{ env.DISTRIBUTION }}
      - name: JMH httpheaders
        run: ${{ env.GRADLE_COMMAND }} clean :httpheaders:jmh
