name: benchmark

on:
  workflow_dispatch:

permissions:
  contents: read

env:
  JDK: '17'
  DISTRIBUTION: 'zulu'
  GRADLE_COMMAND: './gradlew --no-daemon'
  OS: 'ubuntu-latest'

jobs:
  setup:
    runs-on: ${{ env.OS }}
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - id: set-matrix
        run: echo "::set-output name=matrix::`./gradlew -q benchmarkJson"
  benchmark:
    name:  ${{ matrix.microbenchmark }}
    runs-on: ${{ env.OS }}
    needs: setup-benchmark-matrix
    strategy:
      matrix:
        microbenchmark: ${{fromJSON(needs.setup.outputs.matrix)}}
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK ${{ env.JDK }}
        uses: actions/setup-java@v3
        with:
          java-version: ${{ env.JDK }}
          distribution: ${{ env.DISTRIBUTION }}
      - name: JMH
        run: ${{ env.GRADLE_COMMAND }} clean jmh
